services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
      - '6006:6006'
      - '5555:5555'
    volumes:
      - .:/app
      - app_node_modules:/app/node_modules
      - pnpm_store:/root/.pnpm-store
      - next_cache:/app/.next
    env_file:
      - .env.local
    environment:
      - NEXT_SHARP_PATH=/app/node_modules/sharp
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin -d apadana']
      interval: 1s
      timeout: 1s
      retries: 30
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=apadana
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command:
      ['postgres', '-c', 'log_statement=none', '-c', 'log_min_messages=panic']

volumes:
  app_node_modules:
  pnpm_store:
  next_cache:
  postgres_data:
