# Base stage
FROM node:22.11.0-slim AS base


# Install build tools
RUN apt-get update && apt-get install -y \
  python3 \
  make \
  g++ \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Install pnpm
RUN corepack enable && corepack prepare pnpm@9.9.0 --activate

# Install inotify-tools for file watching
RUN apt-get update && apt-get install -y inotify-tools && rm -rf /var/lib/apt/lists/*
# Set pnpm store directory
RUN pnpm config set store-dir /root/.pnpm-store

# update-notifier=false
RUN pnpm config set update-notifier false
# node deprecation warnings off
RUN pnpm config set node-deprecation-warnings false

# Copy package files
COPY package.json pnpm-lock.yaml ./

# Install dependencies with cache
RUN --mount=type=cache,target=/root/.pnpm-store pnpm install --frozen-lockfile --ignore-scripts

# Copy the rest of the application
COPY . .

RUN echo "PRISMA_OUTPUT_DIR=../src/__generated__/prisma" >> .env.local

# Generate Prisma client
RUN pnpm prisma:generate

# Development stage
FROM base AS dev

# Seed the database
RUN pnpm prisma:seed

# Expose ports for Next.js, Storybook, and Prisma Studio
EXPOSE 3000 6006 5555

# Copy entrypoint script
COPY docker-entrypoint.dev.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.dev.sh



ENTRYPOINT ["docker-entrypoint.dev.sh"]
CMD ["pnpm", "run", "dev"]