services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '3030:3030'
    environment:
      - DATABASE_URL=postgresql://admin:admin@db:5432/apadana
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - PRISMA_HIDE_UPDATE_MESSAGE=true
      - STORYBOOK_TELEMETRY_DEBUG=1
      - NEXT_SHARP_PATH=/app/node_modules/sharp
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
        tag: '{{.Name}}'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3030/api/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  db:
    image: postgres:16.6
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin -d apadana']
      interval: 1s
      timeout: 1s
      retries: 5
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=apadana
    volumes:
      - postgres_data:/var/lib/postgresql/data
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
        tag: '{{.Name}}'
    command:
      ['postgres', '-c', 'log_statement=none', '-c', 'log_min_messages=warning']
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G
    restart: unless-stopped

volumes:
  postgres_data:
