services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - NEXT_PUBLIC_S3_UPLOAD_BUCKET=${NEXT_PUBLIC_S3_UPLOAD_BUCKET}
        - NEXT_PUBLIC_DOMAIN=${NEXT_PUBLIC_DOMAIN}
        - NEXT_PUBLIC_S3_UPLOAD_REGION=${NEXT_PUBLIC_S3_UPLOAD_REGION}
    ports:
      - '3000:3000'
      - '6006:6006'
      - '5555:5555'
    volumes:
      - .:/app
      - app_node_modules:/app/node_modules
      - pnpm_store:/root/.pnpm-store
      - next_cache:/app/.next
      - ./package.json:/app/package.json:delegated
    env_file:
      - .env.local
    environment:
      - NEXT_SHARP_PATH=/app/node_modules/sharp
      - NODE_ENV=development
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8G
        reservations:
          cpus: '1'
          memory: 4G
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
        tag: '{{.Name}}'
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  db:
    image: postgres:16
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin -d apadana']
      interval: 1s
      timeout: 1s
      retries: 30
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=apadana
    volumes:
      - postgres_data:/var/lib/postgresql/data
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
        tag: '{{.Name}}'
    command:
      ['postgres', '-c', 'log_statement=none', '-c', 'log_min_messages=panic']

volumes:
  app_node_modules:
  pnpm_store:
  next_cache:
  postgres_data:
