services:
  app_prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '3030:3030'
    env_file:
      - .env.local
    environment:
      - PORT=3030
      - DATABASE_URL=postgresql://admin:admin@db_prod:5432/apadana
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_SHARP_PATH=/app/node_modules/sharp
      - NEXT_PUBLIC_DOMAIN=http://localhost:3030
      - NEXT_PUBLIC_API_URL=http://localhost:3030/api
      - PRISMA_HIDE_UPDATE_MESSAGE=true
      - PRISMA_BINARY_TARGETS=native,linux-arm64-openssl-3.0.x,linux-musl-openssl-3.0.x
      - PRISMA_CLI_QUERY_ENGINE_TYPE=binary
      - STORYBOOK_TELEMETRY_DEBUG=1
      - TEST_ENV=e2e
        # this is also added in Dockerfile.dev. maybe we can remove it from here?
      - PRISMA_OUTPUT_DIR=node_modules/.prisma/client
    depends_on:
      db_prod:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
        tag: '{{.Name}}'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3030/api/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  db_prod:
    image: postgres:16.6
    ports:
      - '5433:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin -d apadana']
      interval: 1s
      timeout: 1s
      retries: 5
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=apadana
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
        tag: '{{.Name}}'
    command:
      ['postgres', '-c', 'log_statement=none', '-c', 'log_min_messages=warning']
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G
    restart: unless-stopped

volumes:
  postgres_data_prod:
