version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
      - "6006:6006"
      - "5555:5555"
    volumes:
      - .:/app
      - app_node_modules:/app/node_modules
      - pnpm_store:/root/.pnpm-store
      - next_cache:/app/.next
    environment:
      - DATABASE_URL=postgresql://admin:admin@db:5432/apadana
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - WATCHPACK_POLLING=true
    depends_on:
      - db

  db:
    image: postgres:16.6
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d apadana" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=apadana
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  app_node_modules:
  pnpm_store:
  next_cache:
  postgres_data:
