version: "3"

vars:
  PRODUCTION_DOMAIN: https://www.apadana.app
  DEVELOPMENT_DOMAIN: https://dev.apadana.local
  PROD_DEV_DOMAIN: https://prod.apadana.local
  PRISMA_SCHEMA: src/prisma/schema.prisma
  DOCKER_COMPOSE: src/docker/docker-compose.yml
  VITEST_CONFIG: config/vitest.config.ts
  STORYBOOK_CONFIG: config/playwright.storybook.config.ts
  E2E_CONFIG: src/e2e/playwright.config.ts
  E2E_TESTING_SECRET_DEV: e2e_testing_secret_for_dev
  E2E_TESTING_SECRET_PROD: e2e_testing_secret_for_prod
  NON_ESLINT_FILES: "**/*.{json,css,md,webmanifest,yml,yaml}"
  ESLINT_FILES: "**/*.{js,jsx,ts,tsx,mjs}"
  ESLINT_CONFIG: config/eslint.config.mjs
  CDK_SCRIPTS: src/aws-setup/scripts
  SCRIPTS: src/scripts
  # Standardized environment names
  ENV:
    sh: echo "${VERCEL_ENV:-${AWS_DEPLOYMENT_STACK_ENV:-development}}"

env:
  DOCKER_BUILDKIT: "1"
  COMPOSE_DOCKER_CLI_BUILD: "1"
  AVOID_UPDATE_NOTIFIER: "1"
  NODE_OPTIONS: --no-warnings
  # Export standardized environment
  AWS_DEPLOYMENT_STACK_ENV:
    sh: echo ${ENV}

tasks:
  i:
    desc: Alias for install
    cmds:
      - task: install
  install:
    desc: Install dependencies
    cmds:
      - pnpm install --prefer-offline

  fetch:
    desc: Fetch dependencies
    cmds:
      - pnpm fetch

  build:
    desc: Build the application
    deps: [prisma:generate]
    cmds:
      - pnpm next build {{.CLI_ARGS}}

  next:start:
    desc: Start Next.js production server
    cmds:
      - pnpm next start {{.CLI_ARGS}}

  dev:
    desc: Start development environment
    deps: [prisma:generate, prisma:migrate]
    cmds:
      - task: dev:all:parallel

  dev:all:parallel:
    internal: true
    cmds:
      - pnpm concurrently "task dev:next" "task dev:prisma" "task dev:storybook"

  dev:next:
    desc: Start Next.js development server
    cmds:
      - pnpm next dev --turbo {{.CLI_ARGS}}

  dev:prisma:
    desc: Watch Prisma schema changes
    cmds:
      - pnpm prisma generate --schema={{.PRISMA_SCHEMA}} --no-hints --watch

  dev:prisma:migrate:
    desc: Run Prisma migrations
    cmds:
      - pnpm prisma migrate dev --schema={{.PRISMA_SCHEMA}} --name $(date +%Y%m%d%H%M%S) {{.CLI_ARGS}}

  dev:prisma:seed:
    desc: Seed the database
    deps: [prisma:generate]
    cmds:
      - pnpm prisma db seed

  dev:prisma:studio:
    desc: Start Prisma Studio
    watch: true
    sources:
      - "{{.PRISMA_SCHEMA}}"
    cmds:
      - pnpm prisma studio --schema={{.PRISMA_SCHEMA}} --browser none {{.CLI_ARGS}}

  dev:storybook:
    desc: Start Storybook development server
    cmds:
      - pnpm storybook dev --quiet --port=6006 --no-open {{.CLI_ARGS}} | grep -v -iE 'info|warn' | grep -v '^$'

  docker:build:
    desc: Build Docker images
    cmds:
      - docker-compose -f {{.DOCKER_COMPOSE}} build --parallel {{.CLI_ARGS}}

  docker:clean:
    desc: Clean Docker volumes
    cmds:
      - docker-compose -f {{.DOCKER_COMPOSE}} down -v

  docker:dev:
    desc: Start development Docker environment
    deps: [docker:build]
    cmds:
      - docker-compose -f {{.DOCKER_COMPOSE}} up app_dev

  docker:down:
    desc: Stop Docker containers
    cmds:
      - docker-compose -f {{.DOCKER_COMPOSE}} down

  docker:prod:
    desc: Start production Docker environment
    deps: [docker:build]
    cmds:
      - docker-compose -f {{.DOCKER_COMPOSE}} up app_prod

  docker:prod:rebuild:
    desc: Rebuild production Docker image
    cmds:
      - docker-compose -f {{.DOCKER_COMPOSE}} build app_prod --parallel

  docker:prod:redeploy:
    desc: Rebuild and restart production container
    deps: [docker:prod:rebuild]
    cmds:
      - docker-compose -f {{.DOCKER_COMPOSE}} up -d --no-deps app_prod

  docker:prune:
    desc: Prune Docker system
    cmds:
      - docker system prune -af --volumes

  t:
    desc: Alias for test
    cmds:
      - task: test:all

  test:all:
    desc: Run all tests in parallel
    cmds:
      - task -p test:unit test:e2e test:storybook

  test:sequential:
    desc: Run all tests sequentially
    cmds:
      - task: test:unit
      - task: test:e2e
      - task: test:storybook

  test:unit:
    desc: Run unit tests
    cmds:
      - pnpm vitest run --config={{.VITEST_CONFIG}} {{.CLI_ARGS}}

  test:e2e:
    desc: Run E2E tests against prod environment
    deps: [nextjs:check:health:prod]
    env:
      E2E_TESTING_SECRET: "{{.E2E_TESTING_SECRET_PROD}}"
      BASE_URL: "{{.PROD_DEV_DOMAIN}}"
    cmds:
      - pnpm playwright test --config={{.E2E_CONFIG}} {{.CLI_ARGS}}

  test:e2e:ci:
    desc: Run E2E tests in CI
    cmds:
      - pnpm playwright test --config={{.E2E_CONFIG}} {{.CLI_ARGS}}

  test:e2e:dev:
    desc: Run E2E tests against dev environment
    env:
      E2E_TESTING_SECRET: "{{.E2E_TESTING_SECRET_DEV}}"
      BASE_URL: "{{.DEVELOPMENT_DOMAIN}}"
    cmds:
      - pnpm playwright test --config={{.E2E_CONFIG}} {{.CLI_ARGS}}

  test:e2e:prod:
    desc: Run E2E tests against production
    env:
      BASE_URL: "{{.PRODUCTION_DOMAIN}}"
    cmds:
      - pnpm playwright test --config={{.E2E_CONFIG}} {{.CLI_ARGS}}

  test:e2e:docker:run:internal:
    internal: true
    desc: Run E2E tests in Docker
    cmds:
      - docker compose -f {{.DOCKER_COMPOSE}} up playwright {{.CLI_ARGS}}

  test:e2e:docker:
    desc: Run E2E tests in Docker
    deps:
      - task: test:e2e:docker:run:internal
    prompt: Do you want to open the HTML report?
    cmds:
      - pnpm playwright show-report .next/playwright-report/html

  test:storybook:
    desc: Run Storybook tests
    cmds:
      - pnpm playwright test --config={{.STORYBOOK_CONFIG}} {{.CLI_ARGS}}

  test:storybook:update:
    desc: Update Storybook test snapshots
    cmds:
      - pnpm playwright test --config={{.STORYBOOK_CONFIG}} --update-snapshots

  test:storybook:docker:
    desc: Run Storybook tests in Docker
    cmds:
      - docker compose -f {{.DOCKER_COMPOSE}} up storybook-test
      - pnpm playwright show-report .next/storybook-report/html

  test:storybook:docker:update:
    desc: Run Storybook tests in Docker and update snapshots
    env:
      UPDATE_SNAPSHOTS: true
    cmds:
      - docker compose -f {{.DOCKER_COMPOSE}} up storybook-test
      - pnpm playwright show-report .next/storybook-report/html

  fix:
    desc: Fix all code issues in parallel
    cmds:
      - task -p lint:fix format

  format:
    desc: Format code
    cmds:
      - pnpm prettier -w {{.NON_ESLINT_FILES}}

  format:check:
    desc: Check code formatting
    cmds:
      - pnpm prettier -c {{.NON_ESLINT_FILES}}

  lint:
    desc: Lint code
    cmds:
      - pnpm eslint --config={{.ESLINT_CONFIG}} {{.CLI_ARGS}}

  lint:fix:
    desc: Fix linting issues
    cmds:
      - pnpm eslint --config={{.ESLINT_CONFIG}} --fix {{.CLI_ARGS}}

  lint:strict:
    desc: Lint code with strict rules
    cmds:
      - pnpm eslint --max-warnings=0 --config={{.ESLINT_CONFIG}} {{.CLI_ARGS}}

  cdk:
    desc: AWS CDK related tasks
    deps: [cdk:preflight]
    cmds:
      - task: cdk:deploy

  cdk:deploy:
    desc: Deploy a specific stack to AWS
    cmds:
      - pnpm cdk deploy {{.CLI_ARGS}}

  cdk:deploy-ci:
    desc: Deploy CDK stack in CI. This will not ask for approval and will deploy all resources.
    cmds:
      - pnpm cdk deploy --all --require-approval never --concurrency 10 {{.CLI_ARGS}}

  cdk:deploy:prod:
    desc: Deploy CDK stack in production
    env:
      AWS_DEPLOYMENT_STACK_ENV: production
      AWS_PROFILE: ap-deployer-production
    cmds:
      - pnpm cdk deploy --all --concurrency 10 {{.CLI_ARGS}} --require-approval never

  cdk:deploy:preview:
    desc: Deploy CDK stack in preview
    env:
      AWS_DEPLOYMENT_STACK_ENV: preview
      AWS_PROFILE: ap-deployer-preview
    cmds:
      - pnpm cdk deploy --all --concurrency 10 {{.CLI_ARGS}} --require-approval never

  cdk:deploy:dev:
    desc: Deploy CDK stack in development
    env:
      AWS_DEPLOYMENT_STACK_ENV: development
      AWS_PROFILE: ap-deployer-development
    cmds:
      - pnpm cdk deploy --all --concurrency 10 {{.CLI_ARGS}} --require-approval never

  cdk:deployer:create:
    desc: Create CDK deployer
    cmds:
      - pnpm tsx {{.CDK_SCRIPTS}}/create-deployer.ts

  cdk:deployer:create:add-to-vercel:
    desc: Add CDK deployer to Vercel
    cmds:
      - pnpm tsx {{.CDK_SCRIPTS}}/create-deployer.ts --add-to-vercel

  cdk:destroy:
    desc: Destroy CDK stack
    cmds:
      - pnpm cdk destroy --all {{.CLI_ARGS}}

  cdk:diff:
    desc: Show CDK diff
    cmds:
      - pnpm cdk diff {{.CLI_ARGS}}

  cdk:preflight:
    desc: Run CDK preflight checks
    cmds:
      - pnpm tsx {{.CDK_SCRIPTS}}/preflight.ts

  cdk:env:
    desc: Print CDK deployment values
    cmds:
      - pnpm tsx {{.CDK_SCRIPTS}}/print-deployment-values.ts

  cdk:synth:
    desc: Synthesize CDK app
    cmds:
      - pnpm cdk synth

  cdk:wait:
    desc: Wait for CDK resources
    cmds:
      - pnpm tsx {{.CDK_SCRIPTS}}/wait-for-ready.ts

  setup:local:
    desc: Setup local development environment
    cmds:
      - pnpm tsx {{.SCRIPTS}}/setup-local-dev.ts

  start:
    desc: Start the application
    deps: [vercel:env:pull, setup:local]
    cmds:
      - docker-compose -f {{.DOCKER_COMPOSE}} up --build

  typecheck:
    desc: Run TypeScript type checking
    deps: [prisma:generate]
    cmds:
      - pnpm tsc --noEmit --incremental false {{.CLI_ARGS}}

  prisma:generate:
    desc: Generate Prisma client
    cmds:
      - pnpm prisma generate --schema={{.PRISMA_SCHEMA}} --no-hints {{.CLI_ARGS}}

  prisma:migrate:
    desc: Run Prisma migrations
    cmds:
      - pnpm prisma migrate deploy --schema={{.PRISMA_SCHEMA}} {{.CLI_ARGS}}

  prisma:watch:
    desc: Watch Prisma schema changes
    watch: true
    sources:
      - prisma/schema.prisma
    cmds:
      - pnpm prisma generate --schema={{.PRISMA_SCHEMA}} --no-hints

  update-packages:
    desc: Update npm packages
    cmds:
      - pnpm tsx {{.SCRIPTS}}/update-packages.ts

  vercel:deploy:
    desc: Deploy to Vercel
    cmds:
      - pnpm vercel deploy {{.CLI_ARGS}}

  vercel:deploy:prod:
    desc: Deploy to Vercel production
    cmds:
      - pnpm vercel deploy --target production --logs {{.CLI_ARGS}}

  vercel:deploy:preview:
    desc: Deploy to Vercel preview
    cmds:
      - pnpm vercel deploy --target preview --logs {{.CLI_ARGS}}

  vercel:env:pull:
    desc: Pull Vercel environment variables
    cmds:
      - pnpm vercel env pull

  cdk:validate-deployer:
    desc: Validate CDK deployer configuration
    cmds:
      - pnpm tsx {{.CDK_SCRIPTS}}/validate-deployer.ts

  nextjs:check:health:prod:
    desc: Check if Dockerized production environment is healthy
    silent: true
    cmds:
      - |
        if curl -s {{.PROD_DEV_DOMAIN}}/api/health | grep -q "healthy"; then
          exit 0
        fi
        echo "Production environment is not healthy"
        exit 1
  serialize-repo:
    desc: Serialize the repository. Provide a path to a file to serialize to using -- --path=<path>
    silent: true
    cmds:
      - pnpm tsx {{.SCRIPTS}}/serialize-repo.ts {{.CLI_ARGS}}
