# Output directory
output_dir = "./repo-serialized"

# Add patterns to ignore (in addition to .gitignore)
ignore_patterns =[
  # Generated files and directories
  '.next/',
  '.cache/',
  'node_modules/',
  '.vercel/',
  '.turbo/',
  'coverage/',
  'storybook-static/',
  'storybook-e2e-html-report/',
  'storybook-e2e-test-results/',
  'test-results/',
  'repo-serialized/',
  
  # Environment and local files
  '.env.local',
  '.env.development.local',
  '.env.test.local',
  '.env.production.local',
  'test.env',
  '.DS_Store',
  'Thumbs.db',
  
  # Lock files and large generated files
  'pnpm-lock.yaml',
  'yarn.lock',
  'package-lock.json'
]

# Define priority rules for processing order
# Higher scores are processed first
[[priority_rules]]
score = 100
pattern = "^prisma/schema\\.prisma$"

[[priority_rules]]
score = 95
pattern = "^package\\.json$"

[[priority_rules]]
score = 90
pattern = "^src/"
