# syntax=docker/dockerfile:1.4

FROM apadana-base:dev
WORKDIR /app

EXPOSE 3000 6006 5555

COPY . .

COPY src/docker/docker-entrypoint.dev.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.dev.sh

ENTRYPOINT ["docker-entrypoint.dev.sh"]

