FROM mcr.microsoft.com/playwright:v1.42.1-jammy

WORKDIR /app

# Install pnpm
RUN corepack enable && corepack prepare pnpm@latest --activate

# Install dependencies
COPY pnpm-lock.yaml ./
RUN pnpm fetch
COPY package.json ./
RUN pnpm install --frozen-lockfile --prefer-offline

COPY . .

# Install Playwright browsers
RUN pnpm exec playwright install --with-deps chromium

