name: 'Test Report Action'
description: 'Creates or updates a check run with test report URL'

inputs:
  test-name:
    description: 'Name of the test suite (e.g., E2E Tests, Storybook Tests)'
    required: true
  test-outcome:
    description: 'Outcome of the test run'
    required: true
  report-url:
    description: 'URL to the test report'
    required: true
  github-token:
    description: 'GitHub token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Create or Update Check with Report URL
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const checkName = '${{ inputs.test-name }}';
          // Try to find existing check
          const { data: checks } = await github.rest.checks.listForRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: context.sha,
            check_name: checkName
          });

          const params = {
            owner: context.repo.owner,
            repo: context.repo.repo,
            name: checkName,
            head_sha: context.sha,
            status: 'completed',
            conclusion: '${{ inputs.test-outcome }}',
            details_url: '${{ inputs.report-url }}'
          };

          if (checks.check_runs.length > 0) {
            // Update existing check
            await github.rest.checks.update({
              check_run_id: checks.check_runs[0].id,
              ...params
            });
          } else {
            // Create new check
            await github.rest.checks.create(params);
          }
