name: 'Test Report Action'
description: 'Creates or updates a check run with test report URL'

inputs:
  test-name:
    description: 'Name of the test suite (e.g., E2E Tests, Storybook Tests)'
    required: true
  test-outcome:
    description: 'Outcome of the test run'
    required: true
  report-url:
    description: 'URL to the test report'
    required: true
  app-id:
    description: 'GitHub App ID'
    required: true
  private-key:
    description: 'GitHub App private key'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Create or Update Check with Report URL
      shell: bash
      env:
        INPUT_APP_ID: ${{ inputs.app-id }}
        INPUT_TEST_NAME: ${{ inputs.test-name }}
        INPUT_TEST_OUTCOME: ${{ inputs.test-outcome }}
        INPUT_REPORT_URL: ${{ inputs.report-url }}
        PRIVATE_KEY: ${{ inputs.private-key }}
      run: node $GITHUB_ACTION_PATH/index.mjs
