export const AWS_PERMISSIONS = [
  'cloudformation:*',
  'ssm:*',
  's3:*',
  'iam:*',
  'lambda:*',
  'ec2:*',
  'elasticache:*',
  'rds:*',
  'secretsmanager:GetSecretValue',
  'secretsmanager:DescribeSecret',
  'secretsmanager:ListSecrets',
  'logs:*',
  'apigateway:*',
  'execute-api:*',
  'route53:*',
  'acm:*',
  'cloudfront:*',
  'events:*',
  'sns:*',
  'sqs:*',
  'dynamodb:*',
  'kms:*',
  'cloudwatch:*',
  'waf:*',
  'wafv2:*',
  'elasticloadbalancing:*',
] as const;

export const AWS_MANAGED_POLICIES = [
  'arn:aws:iam::aws:policy/AWSCloudFormationFullAccess',
  'arn:aws:iam::aws:policy/AmazonSSMFullAccess',
  'arn:aws:iam::aws:policy/AmazonS3FullAccess',
  'arn:aws:iam::aws:policy/IAMFullAccess',
  'arn:aws:iam::aws:policy/AWSLambda_FullAccess',
  'arn:aws:iam::aws:policy/AmazonEC2FullAccess',
  'arn:aws:iam::aws:policy/AmazonElastiCacheFullAccess',
  'arn:aws:iam::aws:policy/AmazonRDSFullAccess',
  'arn:aws:iam::aws:policy/SecretsManagerReadWrite',
  'arn:aws:iam::aws:policy/AmazonAPIGatewayAdministrator',
  'arn:aws:iam::aws:policy/CloudFrontFullAccess',
  'arn:aws:iam::aws:policy/AmazonRoute53FullAccess',
  'arn:aws:iam::aws:policy/AWSCertificateManagerFullAccess',
  'arn:aws:iam::aws:policy/CloudWatchFullAccess',
  'arn:aws:iam::aws:policy/AmazonSNSFullAccess',
  'arn:aws:iam::aws:policy/AmazonSQSFullAccess',
  'arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess',
  'arn:aws:iam::aws:policy/AWSKeyManagementServicePowerUser',
  'arn:aws:iam::aws:policy/AWSWAFFullAccess',
  'arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess',
] as const;
