name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches: ['main']

permissions:
  contents: write
  pull-requests: write
  actions: read
  checks: write
  deployments: read
  statuses: read

jobs:
  validate:
    if: github.event_name != 'deployment_status'
    name: Validate
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm-store
            node_modules
            .next/cache
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Lint
        id: lint
        continue-on-error: true
        run: |
          if pnpm run lint:strict; then
            echo "::set-output name=status::success"
            echo "### Lint: passed" >> $GITHUB_STEP_SUMMARY
          else
            echo "::set-output name=status::failure"
            echo "### Lint: failed" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi

      - name: Type check
        id: typecheck
        continue-on-error: true
        run: |
          if pnpm run typecheck; then
            echo "::set-output name=status::success"
            echo "### Type check: passed" >> $GITHUB_STEP_SUMMARY
          else
            echo "::set-output name=status::failure"
            echo "### Type check: failed" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi

      - name: Format check
        id: format
        continue-on-error: true
        run: |
          if pnpm run format:check; then
            echo "::set-output name=status::success"
            echo "### Format check: passed" >> $GITHUB_STEP_SUMMARY
          else
            echo "::set-output name=status::failure"
            echo "### Format check: failed" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi

      - name: Check all results
        if: always()
        run: |
          if [[ "${{ steps.lint.outputs.status }}" == "failure" ]] || \
             [[ "${{ steps.typecheck.outputs.status }}" == "failure" ]] || \
             [[ "${{ steps.format.outputs.status }}" == "failure" ]]; then
            exit 1
          fi

  test:
    if: github.event_name != 'deployment_status'
    name: Run Vitest
    runs-on: ubuntu-latest
    needs: [validate]
    timeout-minutes: 10
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: apadana_test_ci
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm-store
            node_modules
            .next/cache
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - run: touch .env.local
      - uses: docker/setup-buildx-action@v3
      - run: pnpm run test
        env:
          DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/apadana_test_ci'
          TEST_ENV: 'unit'

  fix-and-commit:
    name: Fix and commit code style
    needs: [validate]
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && needs.validate.result == 'failure'
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - uses: ./.github/actions/setup
      - uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm-store
            node_modules
            .next/cache
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout ${{ github.head_ref }}
      - run: pnpm run fix
      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT
      - if: steps.git-check.outputs.changes == 'true'
        run: |
          git add -A
          git commit -m "style: automatically fix code style issues"
          git push
