name: CI
on:
  push:
    branches:
      - main
  pull_request: {}

concurrency:
  group: ${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Cache Next.js build output
        uses: actions/cache@v3
        with:
          path: .next/cache
          key: ${{ runner.os }}-next-${{ hashFiles('next.config.js', 'package.json', 'pnpm-lock.yaml') }}

      - name: Build
        run: pnpm run build
        env:
          DATABASE_URL: 'postgresql://fake:fake@fake:5432/fake'
          RESEND_API_KEY: fake_RESEND_API_KEY
          GOOGLE_MAPS_API_KEY: fake_GOOGLE_MAPS_API_KEY
          NEXT_PUBLIC_DOMAIN: 'https://apadana.app'
          VERCEL_URL: 'apadana.app'
          NEXT_PUBLIC_S3_UPLOAD_BUCKET: fake_NEXT_PUBLIC_S3_UPLOAD_BUCKET
          NEXT_PUBLIC_S3_UPLOAD_REGION: fake_NEXT_PUBLIC_S3_UPLOAD_REGION
          S3_UPLOAD_KEY: fake_S3_UPLOAD_KEY
          S3_UPLOAD_SECRET: fake_S3_UPLOAD_SECRET

  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - run: pnpm run lint:strict

  typecheck:
    name: Type check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - run: pnpm run typecheck

  prettier:
    name: Prettier check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - run: pnpm run format:check

  test:
    name: Run jest
    runs-on: ubuntu-latest
    timeout-minutes: 10
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: apadana_test_ci
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      - run: pnpm run test
        env:
          DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/apadana_test_ci'
          TEST_ENV: 'unit'
