name: CI
on:
  push:
    branches:
      - main
  pull_request: {}

concurrency:
  group: ${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build
        run: pnpm run build
        env:
          DATABASE_URL: 'postgresql://fake:fake@fake:5432/fake'
          RESEND_API_KEY: fake_RESEND_API_KEY
          GOOGLE_MAPS_API_KEY: fake_GOOGLE_MAPS_API_KEY
          NEXT_PUBLIC_DOMAIN: 'https://apadana.app'
          NEXT_PUBLIC_API_URL: 'https://apadana.app/api'
          NEXT_PUBLIC_S3_UPLOAD_BUCKET: fake_NEXT_PUBLIC_S3_UPLOAD_BUCKET
          NEXT_PUBLIC_S3_UPLOAD_REGION: fake_NEXT_PUBLIC_S3_UPLOAD_REGION
          S3_UPLOAD_KEY: fake_S3_UPLOAD_KEY
          S3_UPLOAD_SECRET: fake_S3_UPLOAD_SECRET

  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - run: pnpm run lint:strict

  typecheck:
    name: Type check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - run: pnpm run typecheck

  prettier:
    name: Prettier check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - run: pnpm run format:check

  test:
    name: Run jest
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - run: pnpm run test
        env:
          DATABASE_URL: 'postgresql://fake:fake@fake:5432/fake'
          RESEND_API_KEY: fake-RESEND_API_KEY
          GOOGLE_MAPS_API_KEY: fake-GOOGLE_MAPS_API_KEY
          NEXT_PUBLIC_DOMAIN: 'https://apadana.app'
          NEXT_PUBLIC_API_URL: 'https://apadana.app/api'
          NEXT_PUBLIC_S3_UPLOAD_BUCKET: fake-S3_UPLOAD_BUCKET
          NEXT_PUBLIC_S3_UPLOAD_REGION: fake-S3_UPLOAD_REGION
          S3_UPLOAD_KEY: fake-S3_UPLOAD_KEY
          S3_UPLOAD_SECRET: fake-S3_UPLOAD_SECRET
          TEST_ENV: 'unit'
