name: Playwright Tests

on:
  deployment_status:

permissions:
  contents: read
  pull-requests: write
  actions: read
  checks: write

jobs:
  run-e2es:
    name: Run E2E Tests
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup

      - name: Install Playwright Browsers
        run: pnpm exec playwright install  --with-deps

      - name: Run tests
        uses: nick-fields/retry@v3
        id: test-run
        with:
          max_attempts: 2
          timeout_minutes: 10
          command: pnpm run e2e:ci
        env:
          BASE_URL: ${{ github.event.deployment_status.environment_url }}
          PLAYWRIGHT_START_SERVER: 'false'
          CLERK_PUBLISHABLE_KEY: ${{ secrets.CLERK_PUBLISHABLE_KEY }}
          CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}

      - name: Upload Playwright Test Report
        id: upload-results
        uses: shallwefootball/s3-upload-action@master
        if: always()
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: apadana-e2e
          source_dir: .next/__e2e__reports__
          destination_dir: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Write Comment
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const { sha } = context.payload.deployment;
            const testRunOutcome = '${{ steps.test-run.outcome }}';
            const conclusion = testRunOutcome === 'success' ? 'success' : 'failure';
            const reportUrl = `https://apadana-e2e.s3.amazonaws.com/${sha}/index.html`;

            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'Playwright Test Report',
              head_sha: sha,
              status: 'completed',
              conclusion: conclusion,
              output: {
                title: 'Playwright Test Report',
                summary: `[View the Playwright test report](${reportUrl})`,
                text: `The Playwright E2E tests have ${conclusion === 'success' ? 'passed' : 'failed'}. Click the link above to view the detailed report.`
              }
            });
