name: E2E

on:
  deployment_status:

permissions:
  contents: read
  pull-requests: write
  actions: read
  checks: write
  deployments: read
  statuses: read

jobs:
  run-e2es:
    name: Playwright
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success'
    steps:
      - name: Check if Deployment is successful
        id: check-deployment
        uses: actions/github-script@v7
        with:
          script: |
            const deploymentStatus = await github.rest.repos.getDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: context.payload.deployment.id,
              status_id: context.payload.deployment_status.id
            });

            core.setOutput('deployment_status', deploymentStatus.data.state);
            core.setOutput('deployment_url', deploymentStatus.data.target_url);

            if (deploymentStatus.data.state !== 'success') {
              throw new Error(`Deployment not successful. state: ${deploymentStatus.data.state}`);
            }

      - name: Check if CI workflow have succeeded
        id: check-workflows
        uses: actions/github-script@v7
        with:
          script: |
            try {
              const workflowRuns = await github.rest.actions.getWorkflowRun({
                owner: context.repo.owner,
              repo: context.repo.repo,
              head_sha: context.sha,
            });
            const ciRun = workflowRuns.data.workflow_runs.find(run => run.path === '.github/workflows/ci.yml');
              core.setOutput('ci_status', ciRun.conclusion);
              const failed = ciRun.conclusion !== 'success';
              if (failed) {
                console.log('CI workflow not successful for this SHA.');
                core.setOutput('skip', 'true');
              }
            } catch (error) {
              core.setOutput('skip', 'true');
            }

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Cache Playwright Browsers
        id: playwright-cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          # Cache key based on Playwright version and OS
          key: playwright-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            playwright-${{ runner.os }}-

      - name: Install Playwright Browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpm exec playwright install --with-deps

      - name: Run E2E Tests
        id: test-run
        run: pnpm run e2e:ci
        env:
          BASE_URL: ${{ steps.check-deployment.outputs.deployment_url }}
          VERCEL_AUTOMATION_BYPASS_SECRET: ${{ secrets.VERCEL_AUTOMATION_BYPASS_SECRET }}

      - name: Upload Playwright Test Report
        if: always() && hashFiles('.next/playwrigh-report/**') != ''
        id: upload-results
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: apadana-e2e
          source_dir: '.next/playwright-report'
          destination_dir: ${{ github.event.workflow_run.head_sha || github.sha }}

      - name: Find PR number
        id: find-pr
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const commits = await github.rest.repos.listPullRequestsAssociatedWithCommit({
              owner,
              repo,
              commit_sha: context.sha,
            });

            if (commits.data.length > 0) {
              core.setOutput('pr_number', commits.data[0].number);
            }

      - name: Comment on PR
        if: always() && steps.find-pr.outputs.pr_number
        uses: actions/github-script@v7
        with:
          script: |
            const testStatus = '${{ steps.test-run.outcome }}';
            const deploymentUrl = '${{ steps.check-deployment.outputs.deployment_url }}';
            const locations = '${{ steps.upload-results.outputs.object_locations }}'.split(',');

            // Find the HTML report URL
            const htmlReportUrl = locations.find(url => url.endsWith('index.html'));

            // Read the JSON report
            const jsonReport = require('/Users/mohsen/code/apadana/.next/playwright-report/json/report.json');
            const stats = jsonReport.stats;

            // Calculate test statistics
            const total = stats.expected + stats.unexpected;
            const passed = stats.expected;
            const failed = stats.unexpected;
            const skipped = stats.skipped;
            const duration = Math.round(stats.duration / 1000); // Convert to seconds

            // Format duration
            const minutes = Math.floor(duration / 60);
            const seconds = duration % 60;
            const durationStr = `${minutes}m ${seconds}s`;

            const statusEmoji = testStatus === 'success' ? '✅' : '❌';
            const comment = `## E2E Test Results ${statusEmoji}\n\n` +
                          `Ran[${deploymentUrl}](${deploymentUrl}) ` +
                          `for ${durationStr}\n\n` +
                          `### Summary\n` +
                          `- Total: ${total}\n` +
                          `- Passed: ${passed} ✅\n` +
                          `- Failed: ${failed} ${failed > 0 ? '❌' : ''}\n` +
                          `- Skipped: ${skipped} ${skipped > 0 ? '⏭️' : ''}\n\n` +
                          `[View Full Report](${htmlReportUrl})\n\n` +
                          `<sub>Updated at: ${new Date().toISOString()}</sub>`;

            // Try to find existing comment
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: parseInt(process.env.PR_NUMBER),
            });

            const botComment = comments.find(comment => 
              comment.user.type === 'Bot' && 
              comment.body.includes('E2E Test Results')
            );

            if (botComment) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: comment
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: parseInt(process.env.PR_NUMBER),
                body: comment
              });
            }
        env:
          PR_NUMBER: ${{ steps.find-pr.outputs.pr_number }}
