name: E2E
on:
  deployment_status:

permissions:
  contents: read
  pull-requests: write
  actions: read
  checks: write
  deployments: read
  statuses: read

jobs:
  e2e:
    name: Playwright
    runs-on: ubuntu-24.04
    container:
      image: mcr.microsoft.com/playwright:v1.42.1-jammy
    if: (github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success')
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/playwright

      - name: Run E2E Tests
        id: test-run
        run: |
          if [ "$ENVIRONMENT" = "production" ]; then
            task test:e2e:prod
          else
            task test:e2e:ci
          fi
        env:
          ENVIRONMENT: ${{ github.event.deployment_status.environment }}
          BASE_URL: ${{ github.event.deployment_status.target_url }}
          VERCEL_AUTOMATION_BYPASS_SECRET: ${{ secrets.VERCEL_AUTOMATION_BYPASS_SECRET }}
          E2E_TESTING_SECRET: ${{ secrets.E2E_TESTING_SECRET }}

      - name: Report E2E Results
        if: always() && hashFiles('.next/playwright-report/**') != ''
        uses: ./.github/actions/test-report
        with:
          app-id: '1100607'
          test-name: 'E2E Tests Results'
          test-outcome: ${{ steps.test-run.outcome }}
          private-key: ${{ secrets.APADANA_AUTOMATION_GITHUB_APP_PRIVATE_KEY }}
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: apadana-e2e
          source_dir: '.next/playwright-report'
          destination_dir: ${{ github.sha }}/playwright
          index_html_location_path: 'html/index.html'

  storybook:
    name: Storybook
    runs-on: ubuntu-24.04
    container:
      image: mcr.microsoft.com/playwright:v1.42.1-jammy
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/playwright

      - name: Test Storybook
        id: test-run
        run: task test:storybook
        env:
          VERCEL_AUTOMATION_BYPASS_SECRET: ${{ secrets.VERCEL_AUTOMATION_BYPASS_SECRET }}
          E2E_TESTING_SECRET: ${{ secrets.E2E_TESTING_SECRET }}
          VERCEL_URL: ${{ github.event.deployment_status.target_url }}

      - name: Report Storybook Results
        if: always() && hashFiles('storybook-e2e-html-report/**') != ''
        uses: ./.github/actions/test-report
        with:
          app-id: '1100607'
          test-name: 'Storybook Results'
          test-outcome: ${{ steps.test-run.outcome }}
          private-key: ${{ secrets.APADANA_AUTOMATION_GITHUB_APP_PRIVATE_KEY }}
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: apadana-e2e
          source_dir: 'storybook-e2e-html-report'
          destination_dir: ${{ github.sha }}/storybook
          index_html_location_path: 'storybook/index.html'
