name: Playwright Tests

on:
  deployment_status:

permissions:
  contents: read
  pull-requests: write
  actions: read

jobs:
  run-e2es:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup

      - name: Install Playwright Browsers
        run: pnpm exec playwright install  --with-deps

      - name: Run tests
        run: pnpm run e2e:ci
        env:
          BASE_URL: ${{ github.event.deployment_status.environment_url }}
          PLAYWRIGHT_START_SERVER: 'false'
          CLERK_PUBLISHABLE_KEY: ${{ secrets.CLERK_PUBLISHABLE_KEY }}
          CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}

      - name: Upload Playwright Test Report
        id: upload-results
        uses: shallwefootball/s3-upload-action@master
        if: always()
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: apadana-e2e
          source_dir: .next/__e2e__reports__
          destination_dir: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Find Comment
        uses: peter-evans/find-comment@v3
        if: always()
        id: fc
        continue-on-error: true
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Playwright Test Report

      - name: Create or Update Comment
        uses: peter-evans/create-or-update-comment@v4
        if: always()
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          body: |
            ## Playwright Test Report
            ✅ [View the Playwright test report](https://apadana-e2e.s3.amazonaws.com/${{ github.event.pull_request.head.sha || github.sha }}/index.html)
          edit-mode: replace
