name: Playwright

on:
  push:
    branches:
      - main
      # TODO: remove
      - file-uploadeer

permissions:
  contents: read
  pull-requests: write
  actions: read
  checks: write

jobs:
  run-e2es:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup

      - name: Start Docker Compose
        uses: docker/setup-buildx-action@v3
        with:
          compose-file: docker-compose.prod.yml

      - name: Install Playwright Browsers
        run: pnpm exec playwright install  --with-deps

      - name: Run tests
        id: test-run
        run: pnpm run e2e:ci
        env:
          BASE_URL: http://localhost:3030

      - name: Upload Playwright Test Report
        id: upload-results
        uses: shallwefootball/s3-upload-action@master
        if: always()
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: apadana-e2e
          source_dir: .next/__e2e__reports__
          destination_dir: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Write Comment
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const { sha } = context.payload.deployment;
            const testRunOutcome = '${{ steps.test-run.outcome }}';
            const conclusion = testRunOutcome === 'success' ? 'success' : 'failure';
            const reportUrl = `https://apadana-e2e.s3.amazonaws.com/${sha}/index.html`;

            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'Playwright Report',
              head_sha: sha,
              status: 'completed',
              conclusion: conclusion,
              details_url: reportUrl,
              output: {
                title: 'Playwright Test Report',
                summary: `[**View the Playwright test report**](${reportUrl})`,
                text: `# The Playwright E2E tests have ${conclusion === 'success' ? 'passed' : 'failed'}.` +
                  `\n\nClick [here](${reportUrl}) to view the detailed report.`
              }
            });

      - name: Stop Docker Compose
        if: always()
        run: docker compose -f docker-compose.prod.yml down
