name: Preview Deployment

on:
  pull_request:
    types: [closed]

jobs:
  delete-preview-db:
    runs-on: ubuntu-latest
    if: github.event.action == 'closed'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Delete Preview Database
        env:
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          PR_NUMBER: ${{ github.event.number }}
          POSTGRES_DATABASE: ${{ secrets.POSTGRES_DATABASE }}
        run: pnpm run manage-db delete "preview_db_${PR_NUMBER}"
