name: Preview Deployment

on:
  pull_request:
    types: [closed]

jobs:
  delete-preview-db:
    runs-on: ubuntu-latest
    if: github.event.action == 'closed'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python and PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 postgresql-client

      - name: Delete Preview Database
        env:
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          PR_NUMBER: ${{ github.event.number }}
          POSTGRES_DATABASE: ${{ secrets.POSTGRES_DATABASE }}
        run: |
          ./src/scripts/manage-db.js delete "preview_db_${PR_NUMBER}"
