name: 'Run TODO to Issue'
on:
  push:
  workflow_dispatch:
    inputs:
      MANUAL_COMMIT_REF:
        description: 'The commit ref to run the action on'
        required: true
      MANUAL_BASE_REF:
        description: 'The base commit ref to run the action on'
        required: false
jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v3'
      - name: 'TODO to Issue'
        uses: 'alstr/todo-to-issue-action@master'
        env:
          MANUAL_COMMIT_REF: ${{ inputs.MANUAL_COMMIT_REF }}
          MANUAL_BASE_REF: ${{ inputs.MANUAL_BASE_REF }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
